import { useState } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useGetDoctorBillingReport, getGetDoctorBillingReportQueryKey, useGetDailyCollection, getGetDailyCollectionQueryKey, useGetRevenueChart, getGetRevenueChartQueryKey, useGetAppointmentStats, getGetAppointmentStatsQueryKey, useGetHospitalSettings, getGetHospitalSettingsQueryKey } from "@workspace/api-client-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import { useCurrency } from "@/lib/currency";
import { TrendingUp, Banknote, CreditCard, Smartphone, Users, Calendar, CheckCircle, XCircle, Clock } from "lucide-react";

export function HospitalReports() {
  const { format: fmt, symbol } = useCurrency();

  const { data: billingReport, isLoading: isLoadingBilling } = useGetDoctorBillingReport(
    {},
    { query: { queryKey: getGetDoctorBillingReportQueryKey({}) } }
  );

  const { data: dailyCollection, isLoading: isLoadingCollection } = useGetDailyCollection(
    {},
    { query: { queryKey: getGetDailyCollectionQueryKey({}) } }
  );

  const { data: revenueChart, isLoading: isLoadingRevenue } = useGetRevenueChart(
    {},
    { query: { queryKey: getGetRevenueChartQueryKey({}) } }
  );

  const { data: appointmentStats, isLoading: isLoadingStats } = useGetAppointmentStats(
    {},
    { query: { queryKey: getGetAppointmentStatsQueryKey({}) } }
  );

  return (
    <DashboardLayout>
      <div className="space-y-6 pb-6 sm:pb-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Reports & Analytics</h1>
          <p className="text-muted-foreground mt-2">Comprehensive operational and financial insights</p>
        </div>

        <Tabs defaultValue="billing" className="w-full">
          <TabsList className="flex w-full overflow-x-auto lg:grid lg:w-[600px] lg:grid-cols-4">
            <TabsTrigger value="billing" className="shrink-0 whitespace-nowrap">Doctor Billing</TabsTrigger>
            <TabsTrigger value="collection" className="shrink-0 whitespace-nowrap">Daily Collection</TabsTrigger>
            <TabsTrigger value="revenue" className="shrink-0 whitespace-nowrap">Revenue Chart</TabsTrigger>
            <TabsTrigger value="appointments" className="shrink-0 whitespace-nowrap">Appointments</TabsTrigger>
          </TabsList>

          <TabsContent value="billing" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-primary" />
                  Doctor Billing Report
                </CardTitle>
                <CardDescription>Revenue generated by each doctor</CardDescription>
              </CardHeader>
              <CardContent>
                {isLoadingBilling ? (
                  <Skeleton className="h-[400px] w-full" />
                ) : (
                  <div className="overflow-x-auto">
                  <Table className="min-w-[760px] sm:min-w-full">
                    <TableHeader>
                      <TableRow>
                        <TableHead>Doctor</TableHead>
                        <TableHead>Appointments</TableHead>
                        <TableHead className="text-right">Total Revenue</TableHead>
                        <TableHead className="text-right">Paid Amount</TableHead>
                        <TableHead className="text-right">Unpaid Amount</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {billingReport?.entries?.map((entry, idx) => (
                        <TableRow key={idx}>
                          <TableCell className="font-medium">Dr. {entry.doctorName}</TableCell>
                          <TableCell>{entry.totalAppointments}</TableCell>
                          <TableCell className="text-right font-bold">{fmt(entry.totalRevenue)}</TableCell>
                          <TableCell className="text-right text-green-600">{fmt(entry.paidAmount ?? 0)}</TableCell>
                          <TableCell className="text-right text-red-600">{fmt(entry.unpaidAmount ?? 0)}</TableCell>
                        </TableRow>
                      ))}
                      {!billingReport?.entries?.length && (
                        <TableRow>
                          <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">No data available</TableCell>
                        </TableRow>
                      )}
                    </TableBody>
                  </Table>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="collection" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Banknote className="w-5 h-5 text-primary" />
                  Daily Collection
                </CardTitle>
                <CardDescription>Breakdown of payments received today</CardDescription>
              </CardHeader>
              <CardContent>
                {isLoadingCollection ? (
                  <Skeleton className="h-[200px] w-full" />
                ) : dailyCollection ? (
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                    <div className="p-5 border rounded-xl bg-gradient-to-br from-primary/5 to-primary/10 border-primary/20">
                      <div className="flex items-center gap-2 mb-3">
                        <Banknote className="w-4 h-4 text-primary" />
                        <p className="text-sm font-semibold text-primary">Total Collection</p>
                      </div>
                      <p className="text-3xl font-bold">{fmt(dailyCollection.totalCollection)}</p>
                    </div>
                    <div className="p-5 border rounded-xl bg-card">
                      <div className="flex items-center gap-2 mb-3">
                        <Banknote className="w-4 h-4 text-green-600" />
                        <p className="text-sm font-medium text-muted-foreground">Cash</p>
                      </div>
                      <p className="text-2xl font-bold">{fmt(dailyCollection.cashCollection ?? 0)}</p>
                    </div>
                    <div className="p-5 border rounded-xl bg-card">
                      <div className="flex items-center gap-2 mb-3">
                        <Smartphone className="w-4 h-4 text-blue-600" />
                        <p className="text-sm font-medium text-muted-foreground">UPI / Online</p>
                      </div>
                      <p className="text-2xl font-bold">{fmt((dailyCollection.upiCollection ?? 0) + (dailyCollection.onlineCollection ?? 0))}</p>
                    </div>
                    <div className="p-5 border rounded-xl bg-card">
                      <div className="flex items-center gap-2 mb-3">
                        <CreditCard className="w-4 h-4 text-purple-600" />
                        <p className="text-sm font-medium text-muted-foreground">Card</p>
                      </div>
                      <p className="text-2xl font-bold">{fmt(dailyCollection.cardCollection ?? 0)}</p>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">No data available</div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="revenue" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-primary" />
                  Revenue Trends
                </CardTitle>
                <CardDescription>Monthly revenue overview</CardDescription>
              </CardHeader>
              <CardContent className="h-[400px]">
                {isLoadingRevenue ? (
                  <Skeleton className="h-full w-full" />
                ) : revenueChart && revenueChart.length > 0 ? (
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={revenueChart}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--border))" />
                      <XAxis dataKey="label" stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                      <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `${symbol}${value}`} />
                      <Tooltip
                        cursor={{ fill: 'hsl(var(--muted))' }}
                        contentStyle={{ backgroundColor: 'hsl(var(--card))', borderRadius: '8px', border: '1px solid hsl(var(--border))' }}
                        formatter={(value: any) => [`${fmt(value)}`, "Revenue"]}
                      />
                      <Bar dataKey="revenue" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                ) : (
                  <div className="flex h-full items-center justify-center text-muted-foreground">No data available</div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="appointments" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Calendar className="w-5 h-5 text-primary" />
                  Appointment Statistics
                </CardTitle>
                <CardDescription>Overview of all appointment statuses</CardDescription>
              </CardHeader>
              <CardContent>
                {isLoadingStats ? (
                  <Skeleton className="h-[200px] w-full" />
                ) : appointmentStats ? (
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                    <div className="p-5 border rounded-xl text-center bg-primary/5 border-primary/20">
                      <p className="text-4xl font-bold text-primary">{appointmentStats.total}</p>
                      <div className="flex items-center justify-center gap-1.5 mt-2 text-sm text-muted-foreground">
                        <Users className="w-4 h-4" /> Total
                      </div>
                    </div>
                    <div className="p-5 border rounded-xl text-center bg-green-50 dark:bg-green-900/10 border-green-200 dark:border-green-800">
                      <p className="text-4xl font-bold text-green-600">{appointmentStats.completed}</p>
                      <div className="flex items-center justify-center gap-1.5 mt-2 text-sm text-muted-foreground">
                        <CheckCircle className="w-4 h-4 text-green-500" /> Completed
                      </div>
                    </div>
                    <div className="p-5 border rounded-xl text-center bg-red-50 dark:bg-red-900/10 border-red-200 dark:border-red-800">
                      <p className="text-4xl font-bold text-red-600">{appointmentStats.cancelled}</p>
                      <div className="flex items-center justify-center gap-1.5 mt-2 text-sm text-muted-foreground">
                        <XCircle className="w-4 h-4 text-red-500" /> Cancelled
                      </div>
                    </div>
                    <div className="p-5 border rounded-xl text-center bg-amber-50 dark:bg-amber-900/10 border-amber-200 dark:border-amber-800">
                      <p className="text-4xl font-bold text-amber-600">{appointmentStats.pending}</p>
                      <div className="flex items-center justify-center gap-1.5 mt-2 text-sm text-muted-foreground">
                        <Clock className="w-4 h-4 text-amber-500" /> Pending
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">No data available</div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}
